# Defines what linker should be used for installing Node packages (useful to enable the node-modules plugin), one of: pnp, pnpm and node-modules.
nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-4.5.1.cjs
