[package]
name = "resvg-js"
version = "1.0.0"
authors = ["yisibl <percyley@qq.com>"]
license = "MPL-2.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "1", features = ["serde-json"] }
napi-derive = "1"
resvg = { version = "0.19.0", default-features = false, features = ["filter"] }
usvg = { version = "0.19.0", default-features = false, features = ["export", "filter", "text"] }
svgtypes = "0.8.0"
tiny-skia = "0.6.1"
fontdb = "0.7.0"
log = "0.4"
env_logger = "0.9.0"
serde = { version = "1", features = ["derive"] }

[build-dependencies]
napi-build = "1"

[profile.release]
lto = true # Enable Link Time Optimization
opt-level = 3
# Setting this to 1 may improve the performance of generated code, but may be slower to compile.
# https://doc.rust-lang.org/rustc/codegen-options/index.html#codegen-units
codegen-units = 1
